import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { capture } from '../src/process.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const identity = JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'));
const packed = path.join(root, '.test-artifacts/packed-install/node_modules', identity.name);
const cli = path.join(packed, 'bin/agent-workspace.js');
const directory = await fs.mkdtemp(path.join(root, '.test-artifacts/pack-smoke-'));
const repo = path.join(directory, 'repo'), home = path.join(directory, 'home');
async function command(...args) {
  const result = await capture(process.execPath, [cli, ...args, '--repo', repo, '--home', home, '--json'], root);
  assert.equal(result.code, 0, result.stderr);
  return JSON.parse(result.stdout);
}
await command('init', '--with', 'codex');
assert.ok((await fs.readFile(path.join(repo, '.agent/.gitignore'), 'utf8')).includes('evidence/'));
for (const harness of ['claude', 'gemini', 'antigravity', 'generic']) await command('adapter', 'install', '--with', harness);
assert.equal((await command('doctor')).ok, true);
await fs.copyFile(path.join(packed, 'examples/task.md'), path.join(repo, '.agent/tasks/DEMO-1.md'));
await command('task', 'validate', 'DEMO-1', '--draft');
await command('task', 'approve', 'DEMO-1', '--by', 'smoke-test-authorization-fixture');
await command('prepare', 'DEMO-1', '--brief');
await fs.mkdir(path.join(repo, 'src'), { recursive: true });
await fs.mkdir(path.join(repo, 'test'), { recursive: true });
await fs.copyFile(path.join(packed, 'examples/demo/greet.mjs'), path.join(repo, 'src/greet.mjs'));
const tests = (await fs.readFile(path.join(packed, 'examples/demo/greet.test.mjs'), 'utf8')).replace("'./greet.mjs'", "'../src/greet.mjs'");
await fs.writeFile(path.join(repo, 'test/greet.test.mjs'), tests);
const testResult = await capture(process.execPath, ['--test', 'test/greet.test.mjs'], repo);
assert.equal(testResult.code, 0, testResult.stderr);
await command('evidence', 'init', 'DEMO-1');
const changes = await command('evidence', 'changes', 'DEMO-1');
await command('evidence', 'record', 'DEMO-1', '--kind', 'E4', '--entry', 'changes', '--artifact', changes.artifact, '--description', 'Captured actual changed-file hashes.', '--result', 'passed');
await fs.writeFile(path.join(repo, '.agent/evidence/DEMO-1/tests.txt'), testResult.stdout + testResult.stderr);
await command('evidence', 'record', 'DEMO-1', '--kind', 'E5', '--entry', 'tests', '--artifact', '.agent/evidence/DEMO-1/tests.txt', '--description', 'Observed both demo tests pass.', '--result', 'passed');
const receiptPath = path.join(repo, '.agent/evidence/DEMO-1.json');
const receipt = JSON.parse(await fs.readFile(receiptPath, 'utf8'));
receipt.implementation_complete = true;
receipt.decisions = [{ change: 'Greeting helper', reason: 'Approved AC1/AC2 require explicit and default greetings.' }];
receipt.dod[0].evidence = ['changes', 'tests'];
await fs.writeFile(receiptPath, JSON.stringify(receipt, null, 2));
const review = await command('review', 'prepare', 'DEMO-1');
await fs.writeFile(path.join(repo, '.agent/evidence/DEMO-1/review.txt'), 'Synthetic independent-review fixture solely for package IO testing; not a real human/model review.\n');
await command('review', 'record', 'DEMO-1', '--by', 'synthetic-review-fixture', '--artifact', '.agent/evidence/DEMO-1/review.txt', '--result', 'passed', '--source-digest', review.source_digest, '--contract-sha256', review.contract_sha256);
assert.equal((await command('evidence', 'validate', 'DEMO-1')).valid, true);
assert.equal((await command('task', 'finish', 'DEMO-1')).status, 'done');
console.log('Installed tarball: all five adapters, real demo tests, receipt/review IO and completion gate passed.\nFixture: ' + directory);
