import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import { capture } from '../src/process.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const identity = JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'));
const packed = path.join(root, '.test-artifacts/packed-install/node_modules', identity.name);
const cli = path.join(packed, 'bin/agent-workspace.js');
const directory = await fs.mkdtemp(path.join(root, '.test-artifacts/pack-smoke-'));
const repo = path.join(directory, 'repo'), home = path.join(directory, 'home');
async function command(...args) {
  const result = await capture(process.execPath, [cli, ...args, '--repo', repo, '--home', home, '--json'], root);
  assert.equal(result.code, 0, result.stderr);
  return JSON.parse(result.stdout);
}
const initialized = await command('init');
assert.deepEqual(initialized.repo.platforms, ['codex', 'claude', 'gemini', 'antigravity']);
assert.equal(initialized.repo.skills.created, 7);
assert.ok((await fs.readFile(path.join(repo, '.agent/.gitignore'), 'utf8')).includes('evidence/'));
assert.equal(await command('skills', 'show', 'pipeline'), (await fs.readFile(path.join(repo, '.agent/skills/pipeline/SKILL.md'), 'utf8')).replace(/\r\n/g, '\n'));
assert.equal(await fs.readFile(path.join(home, 'handbook/agent-operations.md'), 'utf8'), await fs.readFile(path.join(packed, 'docs/agent-operations.md'), 'utf8'));
for (const example of ['task.md', 'api-rule.md', 'demo/greet.mjs', 'demo/greet.test.mjs']) {
  assert.equal(await fs.readFile(path.join(home, 'examples', example), 'utf8'), await fs.readFile(path.join(packed, 'examples', example), 'utf8'));
}
assert.ok((await fs.readFile(path.join(repo, 'wiki/INDEX.md'), 'utf8')).includes('Project wiki'));
assert.equal((await command('doctor')).ok, true);
await fs.copyFile(path.join(packed, 'examples/task.md'), path.join(repo, '.agent/tasks/DEMO-1.md'));
await command('task', 'validate', 'DEMO-1', '--draft');
const pending = await capture(process.execPath, [cli, 'task', 'approve', 'DEMO-1', '--by', 'fixture', '--repo', repo, '--home', home, '--json'], root);
assert.notEqual(pending.code, 0, 'A pending shipped example must not approve.');
assert.equal(await fs.stat(path.join(repo, 'src')).catch(() => null), null);
assert.equal(await fs.stat(path.join(repo, 'test')).catch(() => null), null);
const { frontmatter, markdown } = await import(pathToFileURL(path.join(packed, 'src/io.js')).href);
const taskFile = path.join(repo, '.agent/tasks/DEMO-1.md');
const demoTask = frontmatter(await fs.readFile(taskFile, 'utf8'));
demoTask.metadata.discovery.status = 'ready';
demoTask.metadata.discovery.flow = 'New greet helper -> direct demo tests; inspected src/test absent, no existing callers or shared state.';
demoTask.metadata.discovery.sources.push({ kind: 'source', reference: 'Packed smoke inventory: src/test absent.', summary: 'No existing helper/tests or conflicting consumers.' });
await fs.writeFile(taskFile, markdown(demoTask.metadata, demoTask.body));
await command('task', 'approve', 'DEMO-1', '--by', 'smoke-test-authorization-fixture');
await command('prepare', 'DEMO-1', '--brief');
await fs.mkdir(path.join(repo, 'src'), { recursive: true });
await fs.mkdir(path.join(repo, 'test'), { recursive: true });
await fs.copyFile(path.join(packed, 'examples/demo/greet.mjs'), path.join(repo, 'src/greet.mjs'));
const tests = (await fs.readFile(path.join(packed, 'examples/demo/greet.test.mjs'), 'utf8')).replace("'./greet.mjs'", "'../src/greet.mjs'");
await fs.writeFile(path.join(repo, 'test/greet.test.mjs'), tests);
const testResult = await capture(process.execPath, ['--test', 'test/greet.test.mjs'], repo);
assert.equal(testResult.code, 0, testResult.stderr);
await command('evidence', 'init', 'DEMO-1');
const changes = await command('evidence', 'changes', 'DEMO-1');
await command('evidence', 'record', 'DEMO-1', '--kind', 'E4', '--entry', 'changes', '--artifact', changes.artifact, '--description', 'Captured actual changed-file hashes.', '--result', 'passed');
await fs.writeFile(path.join(repo, '.agent/evidence/DEMO-1/tests.txt'), testResult.stdout + testResult.stderr);
await command('evidence', 'record', 'DEMO-1', '--kind', 'E5', '--entry', 'tests', '--artifact', '.agent/evidence/DEMO-1/tests.txt', '--description', 'Observed both demo tests pass.', '--result', 'passed');
const receiptPath = path.join(repo, '.agent/evidence/DEMO-1.json');
const receipt = JSON.parse(await fs.readFile(receiptPath, 'utf8'));
receipt.implementation_complete = true;
receipt.decisions = [{ change: 'Greeting helper', reason: 'Approved AC1/AC2 require explicit and default greetings.' }];
receipt.dod[0].evidence = ['changes', 'tests'];
await fs.writeFile(receiptPath, JSON.stringify(receipt, null, 2));
const review = await command('review', 'prepare', 'DEMO-1');
await fs.writeFile(path.join(repo, '.agent/evidence/DEMO-1/review.txt'), 'Synthetic independent-review fixture solely for package IO testing; not a real human/model review.\n');
await command('review', 'record', 'DEMO-1', '--by', 'synthetic-review-fixture', '--artifact', '.agent/evidence/DEMO-1/review.txt', '--result', 'passed', '--source-digest', review.source_digest, '--contract-sha256', review.contract_sha256);
assert.equal((await command('evidence', 'validate', 'DEMO-1')).valid, true);
assert.equal((await command('task', 'finish', 'DEMO-1')).status, 'done');
console.log('Installed tarball: four platform routers, one shared skills folder, separate wiki, real demo tests, receipt/review IO and completion gate passed.\nFixture: ' + directory);
